### ISSUE TITLE
IP fetched with prefix when configuring ironic

### ISSUE THREAD

**Issue by maelk** [metal3-io/ironic-image#155]
After this change : https://github.com/metal3-io/ironic-image/commit/e4df69305733355e9e77c78c79c0f84c65c5c3db when runnning 
```
[root@ci-test-vm-20200507050740 /]# ip -br add show scope global up dev "provisioning" | awk '{print $3; exit}'
172.22.0.1/24
```
The prefix should be stripped. This prevents ironic from starting properly

**Comment by maelk** [comment]
The error we see in ironic is :
```
2020-05-07 05:29:12.508 25 CRITICAL ironic [-] Unhandled error: ValueError: 172.22.0.1/24 is not IPv4 or IPv6 address
2020-05-07 05:29:12.508 25 ERROR ironic Traceback (most recent call last):
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/bin/ironic-api", line 10, in <module>
2020-05-07 05:29:12.508 25 ERROR ironic     sys.exit(main())
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/ironic/cmd/api.py", line 57, in main
2020-05-07 05:29:12.508 25 ERROR ironic     launcher.wait()
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_service/service.py", line 654, in wait
2020-05-07 05:29:12.508 25 ERROR ironic     self.conf.log_opt_values(LOG, logging.DEBUG)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/cfg.py", line 2593, in log_opt_values
2020-05-07 05:29:12.508 25 ERROR ironic     _sanitize(opt, getattr(group_attr, opt_name)))
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/cfg.py", line 3138, in __getattr__
2020-05-07 05:29:12.508 25 ERROR ironic     return self._conf._get(name, self._group)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/cfg.py", line 2635, in _get
2020-05-07 05:29:12.508 25 ERROR ironic     value, loc = self._do_get(name, group, namespace)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/cfg.py", line 2737, in _do_get
2020-05-07 05:29:12.508 25 ERROR ironic     return (convert(opt.default), loc)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/cfg.py", line 2668, in convert
2020-05-07 05:29:12.508 25 ERROR ironic     self._substitute(value, group, namespace), opt)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/cfg.py", line 2790, in _convert_value
2020-05-07 05:29:12.508 25 ERROR ironic     return opt.type(value)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/types.py", line 728, in __call__
2020-05-07 05:29:12.508 25 ERROR ironic     self.version_checker(value)
2020-05-07 05:29:12.508 25 ERROR ironic   File "/usr/lib/python3.6/site-packages/oslo_config/types.py", line 748, in _check_both_versions
2020-05-07 05:29:12.508 25 ERROR ironic     raise ValueError("%s is not IPv4 or IPv6 address" % address)
2020-05-07 05:29:12.508 25 ERROR ironic ValueError: 172.22.0.1/24 is not IPv4 or IPv6 address
2020-05-07 05:29:12.508 25 ERROR ironic 
```
