### ISSUE TITLE
machine partition creation issue when qcow2 user image is supplied

### ISSUE THREAD

**Issue by kunyi731** [metal3-io/ironic-image#265]
We used to use a raw user OS image format (.img) and it was working fine. After switching to using the qcow2 format, it seems Ironic Python Agent is not happy when attempting to create partitions:

```
2021-05-17 21:01:02.337 2479 ERROR ironic_lib.disk_utils [-] Failed to fix GPT partition on disk /dev/sda for node None. Error: Unexpected error while running command.
Command: blkid /dev/sda --probe
Exit code: 2
Stdout: ''
Stderr: '': oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
2021-05-17 21:01:02.337 2479 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): blkid /dev/sda --match-tag UUID --match-tag PARTUUID execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
2021-05-17 21:01:02.341 2479 DEBUG oslo_concurrency.processutils [-] CMD "blkid /dev/sda --match-tag UUID --match-tag PARTUUID" returned: 2 in 0.004s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
2021-05-17 21:01:02.341 2479 DEBUG oslo_concurrency.processutils [-] 'blkid /dev/sda --match-tag UUID --match-tag PARTUUID' failed. Not Retrying. execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:474
2021-05-17 21:01:02.342 2479 ERROR root [-] Command failed: prepare_image, error: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: '': oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: ''
2021-05-17 21:01:02.342 2479 ERROR root Traceback (most recent call last):
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 174, in run
2021-05-17 21:01:02.342 2479 ERROR root     result = self.execute_method(**self.command_params)
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/standby.py", line 704, in prepare_image
2021-05-17 21:01:02.342 2479 ERROR root     self._stream_raw_image_onto_device(image_info, stream_to)
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/standby.py", line 605, in _stream_raw_image_onto_device
2021-05-17 21:01:02.342 2479 ERROR root     root_uuid = disk_utils.block_uuid(device)
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_lib/disk_utils.py", line 511, in block_uuid
2021-05-17 21:01:02.342 2479 ERROR root     info = get_device_information(dev, fields=['UUID', 'PARTUUID'])
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_lib/disk_utils.py", line 207, in get_device_information
2021-05-17 21:01:02.342 2479 ERROR root     use_standard_locale=True, run_as_root=True)
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_lib/utils.py", line 97, in execute
2021-05-17 21:01:02.342 2479 ERROR root     result = processutils.execute(*cmd, **kwargs)
2021-05-17 21:01:02.342 2479 ERROR root   File "/usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py", line 441, in execute
2021-05-17 21:01:02.342 2479 ERROR root     cmd=sanitized_cmd)
2021-05-17 21:01:02.342 2479 ERROR root oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
2021-05-17 21:01:02.342 2479 ERROR root Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
2021-05-17 21:01:02.342 2479 ERROR root Exit code: 2
2021-05-17 21:01:02.342 2479 ERROR root Stdout: ''
2021-05-17 21:01:02.342 2479 ERROR root Stderr: ''
2021-05-17 21:01:02.342 2479 ERROR root
2021-05-17 21:01:02.676 2479 DEBUG ironic_python_agent.ironic_api_client [-] Heartbeat: announcing callback URL https://21.0.12.32:9999, API version is 1.68 heartbeat /usr/lib/python3.6/site-packages/ironic_python_agent/ironic_api_client.py:162
2021-05-17 21:01:02.718 2479 INFO ironic_python_agent.agent [-] heartbeat successful
2021-05-17 21:01:02.718 2479 INFO ironic_python_agent.agent [-] sleeping before next heartbeat, interval: 133.739396330338
2021-05-17 21:01:02.718 2479 ERROR root [-] Unexpected error dispatching write_image to manager <ironic_python_agent.hardware.GenericHardwareManager object at 0x7f102a092470>: Command execution failed: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: '': ironic_python_agent.errors.CommandExecutionError: Command execution failed: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: ''
2021-05-17 21:01:02.718 2479 ERROR root Traceback (most recent call last):
2021-05-17 21:01:02.718 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py", line 2454, in dispatch_to_managers
2021-05-17 21:01:02.718 2479 ERROR root     return getattr(manager, method)(*args, **kwargs)
2021-05-17 21:01:02.718 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py", line 2324, in write_image
2021-05-17 21:01:02.718 2479 ERROR root     return cmd.wait()
2021-05-17 21:01:02.718 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 89, in wait
2021-05-17 21:01:02.718 2479 ERROR root     raise self.command_error
2021-05-17 21:01:02.718 2479 ERROR root ironic_python_agent.errors.CommandExecutionError: Command execution failed: Unexpected error while running command.
2021-05-17 21:01:02.718 2479 ERROR root Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
2021-05-17 21:01:02.718 2479 ERROR root Exit code: 2
2021-05-17 21:01:02.718 2479 ERROR root Stdout: ''
2021-05-17 21:01:02.718 2479 ERROR root Stderr: ''
2021-05-17 21:01:02.718 2479 ERROR root
2021-05-17 21:01:02.719 2479 ERROR root [-] Error performing deploy_step write_image: Command execution failed: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: '': ironic_python_agent.errors.CommandExecutionError: Command execution failed: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: ''
2021-05-17 21:01:02.719 2479 ERROR root Traceback (most recent call last):
2021-05-17 21:01:02.719 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/deploy.py", line 77, in execute_deploy_step
2021-05-17 21:01:02.719 2479 ERROR root     **kwargs)
2021-05-17 21:01:02.719 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py", line 2454, in dispatch_to_managers
2021-05-17 21:01:02.719 2479 ERROR root     return getattr(manager, method)(*args, **kwargs)
2021-05-17 21:01:02.719 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py", line 2324, in write_image
2021-05-17 21:01:02.719 2479 ERROR root     return cmd.wait()
2021-05-17 21:01:02.719 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 89, in wait
2021-05-17 21:01:02.719 2479 ERROR root     raise self.command_error
2021-05-17 21:01:02.719 2479 ERROR root ironic_python_agent.errors.CommandExecutionError: Command execution failed: Unexpected error while running command.
2021-05-17 21:01:02.719 2479 ERROR root Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
2021-05-17 21:01:02.719 2479 ERROR root Exit code: 2
2021-05-17 21:01:02.719 2479 ERROR root Stdout: ''
2021-05-17 21:01:02.719 2479 ERROR root Stderr: ''
2021-05-17 21:01:02.719 2479 ERROR root
2021-05-17 21:01:02.739 2479 INFO eventlet.wsgi.server [-] ::ffff:21.0.12.28 "GET /v1/commands/ HTTP/1.1" status: 200  len: 249714 time: 0.0017476
2021-05-17 21:01:03.051 2479 ERROR root [-] Command failed: execute_deploy_step, error: Deploy step failed: Error performing deploy_step write_image: Command execution failed: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: '': ironic_python_agent.errors.DeploymentError: Deploy step failed: Error performing deploy_step write_image: Command execution failed: Unexpected error while running command.
Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
Exit code: 2
Stdout: ''
Stderr: ''
2021-05-17 21:01:03.051 2479 ERROR root Traceback (most recent call last):
2021-05-17 21:01:03.051 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/deploy.py", line 77, in execute_deploy_step
2021-05-17 21:01:03.051 2479 ERROR root     **kwargs)
2021-05-17 21:01:03.051 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py", line 2454, in dispatch_to_managers
2021-05-17 21:01:03.051 2479 ERROR root     return getattr(manager, method)(*args, **kwargs)
2021-05-17 21:01:03.051 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py", line 2324, in write_image
2021-05-17 21:01:03.051 2479 ERROR root     return cmd.wait()
2021-05-17 21:01:03.051 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 89, in wait
2021-05-17 21:01:03.051 2479 ERROR root     raise self.command_error
2021-05-17 21:01:03.051 2479 ERROR root ironic_python_agent.errors.CommandExecutionError: Command execution failed: Unexpected error while running command.
2021-05-17 21:01:03.051 2479 ERROR root Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
2021-05-17 21:01:03.051 2479 ERROR root Exit code: 2
2021-05-17 21:01:03.051 2479 ERROR root Stdout: ''
2021-05-17 21:01:03.051 2479 ERROR root Stderr: ''
2021-05-17 21:01:03.051 2479 ERROR root
2021-05-17 21:01:03.051 2479 ERROR root During handling of the above exception, another exception occurred:
2021-05-17 21:01:03.051 2479 ERROR root
2021-05-17 21:01:03.051 2479 ERROR root Traceback (most recent call last):
2021-05-17 21:01:03.051 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 174, in run
2021-05-17 21:01:03.051 2479 ERROR root     result = self.execute_method(**self.command_params)
2021-05-17 21:01:03.051 2479 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/deploy.py", line 82, in execute_deploy_step
2021-05-17 21:01:03.051 2479 ERROR root     raise errors.DeploymentError(msg)
2021-05-17 21:01:03.051 2479 ERROR root ironic_python_agent.errors.DeploymentError: Deploy step failed: Error performing deploy_step write_image: Command execution failed: Unexpected error while running command.
2021-05-17 21:01:03.051 2479 ERROR root Command: blkid /dev/sda --match-tag UUID --match-tag PARTUUID
2021-05-17 21:01:03.051 2479 ERROR root Exit code: 2
2021-05-17 21:01:03.051 2479 ERROR root Stdout: ''
2021-05-17 21:01:03.051 2479 ERROR root Stderr: ''
2021-05-17 21:01:03.051 2479 ERROR root
2021-05-17 21:01:03.052 2479 DEBUG ironic_python_agent.ironic_api_client [-] Heartbeat: announcing callback URL https://21.0.12.32:9999, API version is 1.68 heartbeat /usr/lib/python3.6/site-packages/ironic_python_agent/ironic_api_client.py:162
2021-05-17 21:01:03.088 2479 INFO ironic_python_agent.agent [-] heartbeat successful
2021-05-17 21:01:03.089 2479 INFO ironic_python_agent.agent [-] sleeping before next heartbeat, interval: 123.50160155794512
```

Is there any baremetal operator / Ironic API that should be set during provisioning to use the qcow2 image?

**Comment by furkatgofurov7** [comment]
Hi! Thanks for reporting, can you please provide these:
- can you please give more information what image are you using?
- can you also provide full logs from ramdisk. 

Thank you.

**Comment by dtantsur** [comment]
From reading the man page, exit code 2 means device not found. Is /dev/sda even correct?

**Comment by kunyi731** [comment]
Sorry about the late reply. We have quite several updates in our pipeline. I will test with the latest and provide an update.
