### ISSUE TITLE
Error setting up bootloader. Error UTF-16 stream does not start with BOM: UnicodeError: UTF-16 stream does not start with BOM

### ISSUE THREAD

**Issue by kplimack** [metal3-io/ironic-image#352]
I'm still trying to determing what changed to trigger this.  any help debugging this issue would be much appreciated.
I did login to a host during ironic-inspection and ran `efibootmgr` successfully, but did not see what this CSV file is that its tripping on.  

```
Feb 18 05:45:15 localhost.localdomain ironic-python-agent[2090]: 2022-02-18 05:45:15.259 2090 INFO ironic_lib.disk_utils [-] Disk metadata on /dev/nvme24n1 successfully destroyed for node
Feb 18 05:45:15 localhost.localdomain ironic-python-agent[2090]: 2022-02-18 05:45:15.269 2090 INFO ironic_python_agent.extensions.standby [-] Writing image with command: qemu-img convert -t directsync -S 0 -O host_device -W /tmp/ubuntu-2004-kube-v1.20.10.a-efi.qcow2 /dev/nvme24n1
Feb 18 05:45:37 localhost.localdomain ironic-python-agent[2090]: 2022-02-18 05:45:37.306 2090 INFO ironic_python_agent.extensions.standby [-] Image /tmp/ubuntu-2004-kube-v1.20.10.a-efi.qcow2 written to device /dev/nvme24n1 in 27.08680534362793 seconds
Feb 18 06:09:54 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:09:54.511 2085 INFO root [-] Configdrive for node 83b642eb-3205-4d77-8132-03e931da3b9d successfully copied onto partition /dev/nvme24n1p5

Feb 18 06:10:06 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:02.610 2085 INFO root [-] Asynchronous command install_bootloader started execution
Feb 18 06:10:26 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:26.585 2085 INFO ironic_lib.utils [-] Root device found! The device "{'name': '/dev/nvme24n1', 'model': 'Micron_2300_MTFDHBA512TDV', 'size': 512110190592, 'rotational': False, 'wwn': 'eui.000000000000000100a075212d5a81d8', 'serial': '21092D5A81D8', 'vendor': None, 'wwn_with_extension': 'eui.000000000000000100a075212d5a81d8', 'wwn_vendor_extension': None, 'hctl': None, 'by_path': '/dev/disk/by-path/pci-0000:4b:00.0-nvme-1'}" matches the root device hints {'name': 's== /dev/nvme24n1'}

Feb 18 06:10:26 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:26.585 2085 INFO root [-] Picked root device /dev/nvme24n1 for node 83b642eb-3205-4d77-8132-03e931da3b9d based on root device hints {'name': 's== /dev/nvme24n1'}

Feb 18 06:10:32 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:28.128 2085 WARNING ironic_python_agent.utils [-] Couldn't re-read the partition table on device /dev/nvme24n1: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.

Feb 18 06:10:32 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:32.136 2085 DEBUG ironic_lib.utils [-] Command stdout is: "Model: NVMe Device (nvme)
                                                                 Disk /dev/nvme24n1: 512GB
                                                                 Sector size (logical/physical): 512B/512B
                                                                 Partition Table: gpt
                                                                 Disk Flags:

                                                                 Number  Start   End     Size    File system  Name                  Flags
                                                                  1      17.4kB  1018kB  1000kB                                     bios_grub
                                                                  2      1018kB  201MB   200MB   fat32        EFI System Partition  boot, esp
                                                                  3      201MB   713MB   512MB   ext3
                                                                  4      713MB   21.5GB  20.8GB  ext4
                                                                  5      512GB   512GB   67.1MB


Feb 18 06:10:32 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:32.149 2085 DEBUG ironic_lib.utils [-] Command stdout is: "BYT;
                                                                 /dev/nvme24n1:488386MiB:nvme:512:512:gpt:NVMe Device:;
                                                                 1:0.02MiB:0.97MiB:0.95MiB:::bios_grub;
                                                                 2:0.97MiB:192MiB:191MiB:fat32:EFI System Partition:boot, esp;
                                                                 3:192MiB:680MiB:488MiB:ext3::;
                                                                 4:680MiB:20480MiB:19800MiB:ext4::;
                                                                 5:488322MiB:488386MiB:64.0MiB:::;

Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.144 2085 DEBUG ironic_lib.utils [-] Command stdout is: "BootCurrent: 0003
                                                                 Timeout: 1 seconds
                                                                 BootOrder: 0007,0003,0004,0005,0006,0001
                                                                 Boot0001* UEFI: Built-in EFI Shell        VenMedia(5023b95c-db26-429b-a648-bd47664c8012)..BO
                                                                 Boot0003* (B69/D0/F0) UEFI PXE: IPv4 Supermicro 10GBASE-T Ethernet Controller(MAC:3cecef74610a)        PciRoot(0x1)/Pci(0x3,0x1)/Pci(0x0,0x0)/MAC(3cecef74610a,1)/IPv4(0.0.0.00.0.0.0,0,0)..BO
                                                                 Boot0004* (B69/D0/F1) UEFI PXE: IPv4 Supermicro 10GBASE-T Ethernet Controller(MAC:3cecef74610b)        PciRoot(0x1)/Pci(0x3,0x1)/Pci(0x0,0x1)/MAC(3cecef74610b,1)/IPv4(0.0.0.00.0.0.0,0,0)..BO
                                                                 Boot0005* (B69/D0/F0) UEFI PXE: IPv6 Supermicro 10GBASE-T Ethernet Controller(MAC:3cecef74610a)        PciRoot(0x1)/Pci(0x3,0x1)/Pci(0x0,0x0)/MAC(3cecef74610a,1)/IPv6([::]:<->[::]:,0,0)..BO
                                                                 Boot0006* (B69/D0/F1) UEFI PXE: IPv6 Supermicro 10GBASE-T Ethernet Controller(MAC:3cecef74610b)        PciRoot(0x1)/Pci(0x3,0x1)/Pci(0x0,0x1)/MAC(3cecef74610b,1)/IPv6([::]:<->[::]:,0,0)..BO
                                                                 Boot0007* ubuntu        HD(2,GPT,601b431f-bebe-49b6-afe2-04312ef10c8c,0x7c4,0x5f5e2)/File(\EFI\UBUNTU\SHIMX64.EFI)..BO
                                                                 " _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.145 2085 DEBUG ironic_lib.utils [-] Command stderr is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.145 2085 DEBUG ironic_python_agent.efi_utils [-] A CSV file has been identified as a bootloader hint. File: EFI/ubuntu/BOOTX64.CSV _run_efibootmgr /usr/lib/python3.6/site-packages/ironic_python_agent/efi_utils.py:297
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.150 2085 DEBUG ironic_python_agent.efi_utils [-] Executing _manage_uefi clean-up. manage_uefi /usr/lib/python3.6/site-packages/ironic_python_agent/efi_utils.py:157
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.151 2085 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): umount /tmp/tmp9xbaofp6/boot/efi execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.181 2085 DEBUG oslo_concurrency.processutils [-] CMD "umount /tmp/tmp9xbaofp6/boot/efi" returned: 0 in 0.031s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.182 2085 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.182 2085 DEBUG ironic_lib.utils [-] Command stderr is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.182 2085 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): sync execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.186 2085 DEBUG oslo_concurrency.processutils [-] CMD "sync" returned: 0 in 0.004s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.186 2085 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.186 2085 DEBUG ironic_lib.utils [-] Command stderr is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Feb 18 06:10:40 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.187 2085 ERROR ironic_python_agent.extensions.image [-] Error setting up bootloader. Error UTF-16 stream does not start with BOM: UnicodeError: UTF-16 stream does not start with BOM
Feb 18 06:10:44 localhost.localdomain ironic-python-agent[2085]: 2022-02-18 06:10:40.188 2085 ERROR root [-] Command failed: install_bootloader, error: UTF-16 stream does not start with BOM: UnicodeError: UTF-16 stream does not start with BOM
                                                                 2022-02-18 06:10:40.188 2085 ERROR root Traceback (most recent call last):
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 174, in run
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     result = self.execute_method(**self.command_params)
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py", line 782, in install_bootloader
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     if _efi_boot_setup(device, efi_system_part_uuid, target_boot_mode):
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py", line 660, in _efi_boot_setup
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     device, efi_system_part_uuid=efi_system_part_uuid)
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/efi_utils.py", line 148, in manage_uefi
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     efi_partition_mount_point)
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/efi_utils.py", line 301, in _run_efibootmgr
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     contents = str(csv.read())
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib64/python3.6/codecs.py", line 321, in decode
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     (result, consumed) = self._buffer_decode(data, self.errors, final)
                                                                 2022-02-18 06:10:40.188 2085 ERROR root   File "/usr/lib64/python3.6/encodings/utf_16.py", line 67, in _buffer_decode
                                                                 2022-02-18 06:10:40.188 2085 ERROR root     raise UnicodeError("UTF-16 stream does not start with BOM")
                                                                 2022-02-18 06:10:40.188 2085 ERROR root UnicodeError: UTF-16 stream does not start with BOM
```

**Comment by kplimack** [comment]
@dhellmann do you or TheJulia have any ideas what I can check to debug this?

not sure if this bios_grub partition is supposed to be here.   metadata cleaning wipes it, but imaging puts it back
```
[root@localhost dev]# parted /dev/nvme24n1 print
Model: NVMe Device (nvme)
Disk /dev/nvme24n1: 512GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End     Size    File system  Name                  Flags
 1      17.4kB  1018kB  1000kB                                     bios_grub
 2      1018kB  201MB   200MB   fat32        EFI System Partition  boot, esp
 3      201MB   713MB   512MB   ext3
 4      713MB   21.5GB  20.8GB  ext4
 5      512GB   512GB   67.1MB
 ```

**Comment by elfosardo** [comment]
/triage accepted
we verified this issue doing some troubleshooting on slack
we're guessing the codec of the csv file wrong
a patch to IPA is probably needed to correctly detect the codec in case it's not utf-16 but can be Little Endian or Big Endian

**Comment by elfosardo** [comment]
fix has been proposed  in ironic-python-agent upstream https://review.opendev.org/c/openstack/ironic-python-agent/+/830264

**Comment by elfosardo** [comment]
@kplimack did you get the chance to test the fix?

**Comment by kplimack** [comment]
Yes I did get a chance to test and it works properly.
